In [28]:
import numpy as np
import datetime
import pickle
#import pandas as pd

In [63]:
class FencingPool:
    
    def __init__(self, ident, imported):
        self.ident = ident
        self.date = str(datetime.date.today())
        self.results = imported[0]
        self.names = imported[1]
        
    def get_results(self):
        print(self.results)
        
        
def pool_importer(pool_loc="./pool_test_csv.csv"):
    
    #types = '<U12,i8,i8,i8'
    #pool = np.genfromtxt("./pool_test_csv.csv", delimiter=',', dtype=types, skip_header=1)
    
    with open("./pool_test_csv.csv") as f:
        ncols = len(f.readline().split(','))
    pool = np.genfromtxt("./pool_test_csv.csv", delimiter=',', dtype=None, skip_header=1, usecols=range(1,ncols))
    names = np.genfromtxt("./pool_test_csv.csv", delimiter=',', dtype='<U12', skip_header=1, usecols=0)
    
    return pool, names

def load_database(filename):
    
    with open(filename,'rb') as file_object: 
        db = pickle.load(file_object)
    return db
    
def add_pool_to_database(pool, filename):
    
    db = load_database(filename)
    
    for name in pool.names:
        if name not in db[0]:
            new_id = max(db[1])+1
            db[0][name] = new_id
            db[1][new_id] = name
    
    db[2].append(pool)
    
    with open(filename, 'wb') as file_object:
        pickle.dump(db, file_object)
    
def initialize_database(filename):
    
    db = [{},{1000: 'no student'},[]]    
    with open(filename, 'wb') as file_object:
        pickle.dump(db, file_object)
        
def construct_results_array_from_database(filename):
    
    db = load_database(filename)
    num_fencers = len(database[0])
    num_pools = len(database[2])
    
    results_array = np.zeros((num_pools, num_fencers+1, num_fencers+1), dtype=int)-1
    results_array[:,0,1:] = [*database[1].keys()][1:]
    results_array[:,1:,0] = [*database[1].keys()][1:]
    
    for i in range(len(database[2])):
        results_array[i,0,0] = database[2][i].ident
        results_array[i,1:num_fencers+1,1:num_fencers+1] = database[2][i].results

    return results_array
    


        

In [64]:
pool1 = FencingPool(1, pool_importer())
pool2 = FencingPool(2, pool_importer())
pool3 = FencingPool(3, pool_importer())

In [65]:
filename = 'testfile'

In [66]:
initialize_database(filename)
database = load_database(filename)
print(database)

[{}, {1000: 'no student'}, []]


In [67]:
add_pool_to_database(pool1, filename)
add_pool_to_database(pool2, filename)
add_pool_to_database(pool3, filename)
database = load_database(filename)
print(database)

[{'Alice': 1001, 'Bob': 1002, 'Chuck': 1003}, {1000: 'no student', 1001: 'Alice', 1002: 'Bob', 1003: 'Chuck'}, [<__main__.FencingPool object at 0x000001DB8A8359B0>, <__main__.FencingPool object at 0x000001DB8A835A90>, <__main__.FencingPool object at 0x000001DB8A835A58>]]


In [68]:
results_array = construct_results_array_from_database(filename)

In [69]:
results_array

array([[[   1, 1001, 1002, 1003],
        [1001,   -1,    5,    5],
        [1002,    3,   -1,    5],
        [1003,    1,    2,   -1]],

       [[   2, 1001, 1002, 1003],
        [1001,   -1,    5,    5],
        [1002,    3,   -1,    5],
        [1003,    1,    2,   -1]],

       [[   3, 1001, 1002, 1003],
        [1001,   -1,    5,    5],
        [1002,    3,   -1,    5],
        [1003,    1,    2,   -1]]])

In [91]:
results_array[results_array[:,0,:] == 1001]

array([[1001,   -1,    5,    5],
       [1001,   -1,    5,    5],
       [1001,   -1,    5,    5]])

In [40]:
p = np.zeros((num_pools, num_fencers+1, num_fencers+1), dtype=int)-1
p[:,0,1:] = [*database[1].keys()][1:]
p[:,1:,0] = [*database[1].keys()][1:]
p

array([[[  -1, 1001, 1002, 1003],
        [1001,   -1,   -1,   -1],
        [1002,   -1,   -1,   -1],
        [1003,   -1,   -1,   -1]],

       [[  -1, 1001, 1002, 1003],
        [1001,   -1,   -1,   -1],
        [1002,   -1,   -1,   -1],
        [1003,   -1,   -1,   -1]]])

In [39]:
p[0,1:num_fencers+1,1:num_fencers+1] = database[2][0].results
p

array([[[  -1, 1001, 1002, 1003],
        [1001,   -1,    5,    5],
        [1002,    3,   -1,    5],
        [1003,    1,    2,   -1]],

       [[  -1, 1001, 1002, 1003],
        [1001,   -1,   -1,   -1],
        [1002,   -1,   -1,   -1],
        [1003,   -1,   -1,   -1]]])

In [45]:

for i in range(len(database[2])):
    
    p[i,1:num_fencers+1,1:num_fencers+1] = database[2][i].results

In [46]:
p

array([[[  -1, 1001, 1002, 1003],
        [1001,   -1,    5,    5],
        [1002,    3,   -1,    5],
        [1003,    1,    2,   -1]],

       [[  -1, 1001, 1002, 1003],
        [1001,   -1,    5,    5],
        [1002,    3,   -1,    5],
        [1003,    1,    2,   -1]]])

In [54]:
len(p)

2

In [168]:
r = np.array([[1,2],['s','s']])
r

array([['1', '2'],
       ['s', 's']], 
      dtype='<U11')

In [100]:
r.shape

(2, 2)

In [81]:
p = pool1.results()
q = pool2.results()

In [84]:
r = np.insert(p, p.shape[0] , q, axis=0)
r

array([('Alice', -1,  5,  5), ('Bob',  3, -1,  5), ('Chuck',  1,  2, -1),
       ('Alice', -1,  5,  5), ('Bob',  3, -1,  5), ('Chuck',  1,  2, -1)], 
      dtype=[('f0', '<U12'), ('f1', '<i8'), ('f2', '<i8'), ('f3', '<i8')])

In [88]:
r.shape

(6,)

In [92]:
p

array([('Alice', -1,  5,  5), ('Bob',  3, -1,  5), ('Chuck',  1,  2, -1)], 
      dtype=[('f0', '<U12'), ('f1', '<i8'), ('f2', '<i8'), ('f3', '<i8')])

In [63]:
types = '<U12,i8,i8,i8'

with open("./pool_test_csv.csv") as f:
    ncols = len(f.readline().split(','))
pool = np.genfromtxt("./pool_test_csv.csv", delimiter=',', dtype=None, skip_header=1, usecols=range(1,ncols))
names = np.genfromtxt("./pool_test_csv.csv", delimiter=',', dtype='<U12', skip_header=1, usecols=0)

In [64]:
pool

array([[-1,  5,  5],
       [ 3, -1,  5],
       [ 1,  2, -1]])

In [65]:
names[0]

'Alice'

In [109]:
pool.reshape((3,4))

ValueError: cannot reshape array of size 3 into shape (3,4)

In [119]:
pool1.results()

array([('Alice', -1,  5,  5), ('Bob',  3, -1,  5), ('Chuck',  1,  2, -1)], 
      dtype=[('f0', '<U12'), ('f1', '<i8'), ('f2', '<i8'), ('f3', '<i8')])

In [111]:
[0]

[0]

In [115]:
k = np.zeros(3)
k

array([ 0.,  0.,  0.])

In [167]:
np.array([1,'a',2])

array(['1', 'a', '2'], 
      dtype='<U11')

In [10]:
fd = {'Alice': 3}

In [11]:
fd['Alice']

3

In [14]:
k = [[1],[2]]

In [18]:
k[1].append(3)

In [19]:
k

[[1], [2, 3]]

In [29]:
p ={'k': 3}

In [146]:
max(p)

's'

In [145]:
't' in p

False

In [41]:
p['q'] =3

In [165]:
len(p)

3

In [50]:
try:
    print(p['s'])
except:
    p['s'] = 1

1


In [51]:
p

{'k': 3, 'q': 3, 's': 1}

In [52]:
{}

{}

In [68]:
def g():
    return 3, 4

In [70]:
g()

(3, 4)

In [147]:
max([])

ValueError: max() arg is an empty sequence